"""
SQLAlchemy Model for Security Alerts generated by Detection Rules
"""
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, DateTime, Text, Float
from sqlalchemy.orm import relationship
from app.core.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    alert_type = Column(String(50), index=True, nullable=False)   # BRUTE_FORCE, REPEATED_FAILED_LOGIN, PRIVILEGE_ESCALATION, PORT_SCAN, THREAT_INTEL_IOC, POWERSHELL_OBFUSCATION, MALWARE_HASH, WINDOWS_AUTH_ANOMALY
    severity = Column(String(20), index=True, nullable=False)     # LOW, MEDIUM, HIGH, CRITICAL
    source_ip = Column(String(45), index=True, nullable=True)
    destination_ip = Column(String(45), index=True, nullable=True)
    username = Column(String(100), index=True, nullable=True)
    description = Column(Text, nullable=False)
    rule_id = Column(String(50), index=True, nullable=False)      # RULE-001, RULE-002, etc.
    status = Column(String(20), default="OPEN", index=True)       # OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # MITRE ATT&CK Mapping
    mitre_technique_id = Column(String(50), index=True, nullable=True)   # e.g., T1110, T1059.001, T1046
    mitre_technique_name = Column(String(150), nullable=True)           # e.g., Brute Force, Command and Scripting Interpreter: PowerShell
    mitre_tactic = Column(String(100), index=True, nullable=True)        # e.g., Credential Access, Execution, Discovery

    # Threat Intelligence & Evidence
    ioc_value = Column(String(255), index=True, nullable=True)          # e.g. IP, Hash, Domain
    ioc_type = Column(String(50), nullable=True)                         # ip, hash_sha256, hash_md5, domain
    threat_score = Column(Float, default=0.0)                            # 0.0 - 100.0 Abuse/Malicious confidence
    raw_event_data = Column(Text, nullable=True)                         # JSON or raw log snippet context

    # Relationship to incident (if an incident is created for this alert)
    incident = relationship("Incident", back_populates="alert", uselist=False)

    def __repr__(self):
        return f"<Alert(id={self.id}, rule='{self.rule_id}', type='{self.alert_type}', severity='{self.severity}', status='{self.status}')>"
