"""
Security Alerts API Router: Triage, Lifecycle Management, and Escalation
"""
from typing import Optional, List
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session
from sqlalchemy import desc

from app.core.database import get_db
from app.models.alert import Alert
from app.models.incident import Incident
from app.schemas.alert import AlertResponse, AlertListResponse, AlertUpdate, AlertEscalateRequest
from app.schemas.incident import IncidentResponse

router = APIRouter(
    prefix="/alerts",
    tags=["Security Alerts & Triage"]
)


@router.get("", response_model=AlertListResponse)
def get_alerts(
    severity: Optional[str] = Query(None, description="Filter by severity: LOW, MEDIUM, HIGH, CRITICAL"),
    status_filter: Optional[str] = Query(None, alias="status", description="Filter by status: OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE"),
    rule_id: Optional[str] = Query(None, description="Filter by Rule ID: RULE-001, etc."),
    mitre_tactic: Optional[str] = Query(None, description="Filter by MITRE Tactic"),
    limit: int = Query(50, ge=1, le=500),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db)
):
    """
    List and filter security alerts generated by detection rules with counts breakdown.
    """
    query = db.query(Alert)

    if severity:
        query = query.filter(Alert.severity == severity.upper())
    if status_filter:
        query = query.filter(Alert.status == status_filter.upper())
    if rule_id:
        query = query.filter(Alert.rule_id == rule_id)
    if mitre_tactic:
        query = query.filter(Alert.mitre_tactic.ilike(f"%{mitre_tactic}%"))

    total = query.count()
    alerts = query.order_by(desc(Alert.timestamp)).offset(offset).limit(limit).all()

    # Overall stat counts
    open_count = db.query(Alert).filter(Alert.status == "OPEN").count()
    investigating_count = db.query(Alert).filter(Alert.status == "INVESTIGATING").count()
    critical_count = db.query(Alert).filter(Alert.severity == "CRITICAL").count()
    high_count = db.query(Alert).filter(Alert.severity == "HIGH").count()

    return {
        "total": total,
        "open_count": open_count,
        "investigating_count": investigating_count,
        "critical_count": critical_count,
        "high_count": high_count,
        "alerts": alerts
    }


@router.get("/{alert_id}", response_model=AlertResponse)
def get_alert_by_id(
    alert_id: int,
    db: Session = Depends(get_db)
):
    """
    Get detailed breakdown of a single alert including MITRE technique and raw evidence.
    """
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert ID {alert_id} not found."
        )
    return alert


@router.patch("/{alert_id}/status", response_model=AlertResponse)
def update_alert_status(
    alert_id: int,
    update_req: AlertUpdate,
    db: Session = Depends(get_db)
):
    """
    Update triage status of an alert (OPEN -> INVESTIGATING -> RESOLVED / FALSE_POSITIVE).
    """
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert ID {alert_id} not found."
        )

    if update_req.status:
        alert.status = update_req.status.upper()
    if update_req.description:
        alert.description = update_req.description

    db.commit()
    db.refresh(alert)
    return alert


@router.post("/{alert_id}/escalate", response_model=IncidentResponse, status_code=status.HTTP_201_CREATED)
def escalate_alert_to_incident(
    alert_id: int,
    escalate_req: AlertEscalateRequest,
    db: Session = Depends(get_db)
):
    """
    1-Click SOC Action: Escalate a high-severity alert to an official Incident Case with auto-generated case number.
    """
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert ID {alert_id} not found."
        )

    # Check if already escalated
    existing_incident = db.query(Incident).filter(Incident.alert_id == alert_id).first()
    if existing_incident:
        return existing_incident

    # Generate next incident number: INC-2026-XXXX
    count = db.query(Incident).count() + 1
    year = datetime.now(timezone.utc).year
    inc_num = f"INC-{year}-{count:04d}"

    # Build title & summary
    title = f"{alert.alert_type}: {alert.description[:100]}"
    summary = f"Incident generated from alert #{alert.id} ({alert.rule_id}). Target: {alert.username or 'N/A'}, Source: {alert.source_ip or 'N/A'}."
    
    incident = Incident(
        incident_number=inc_num,
        alert_id=alert.id,
        title=title,
        severity=alert.severity,
        status="INVESTIGATING",
        assigned_to=escalate_req.assigned_to or "soc_analyst",
        summary=summary,
        investigation_notes=escalate_req.initial_notes or f"Automated escalation from Detection Rule {alert.rule_id}.",
        mitre_tactics=alert.mitre_tactic or "Credential Access",
        mitre_techniques=alert.mitre_technique_id or "T1110",
        iocs=alert.ioc_value or alert.source_ip,
        containment_steps="1. Investigating source traffic and assessing potential lateral movement.\n2. Reviewing host integrity.",
        remediation_notes="Review authentication logs and update detection threshold if needed."
    )

    # Update alert status
    alert.status = "INVESTIGATING"

    db.add(incident)
    db.commit()
    db.refresh(incident)
    return incident
